const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
  const errors = [];
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  const base = process.env.GAME_URL || 'http://localhost:5173/';
  fs.mkdirSync('test-results', { recursive: true });
  try {
    await page.goto(`${base}?test=1`);
    await page.locator('.seed-card').first().waitFor();
    assert.equal(await page.locator('.seed-card').count(), 8); assert.equal(await page.locator('.lawn-cell').count(), 45);
    await page.click('#mode-free');
    await page.keyboard.press('2');
    for (let row=0;row<5;row++) for(let col=0;col<9;col++) await page.locator(`[data-row="${row}"][data-col="${col}"]`).click();
    assert.equal(await page.locator('.plant-entity').count(), 45);
    assert.equal(await page.locator('#sun-count').textContent(), '150');
    await page.evaluate(() => __pvz.advance(600));
    assert.equal(await page.evaluate(() => __pvz.game.time), 0);
    assert.equal(await page.evaluate(() => __pvz.game.status), 'ready');
    assert.equal(await page.locator('.zombie-entity, .preview-zombie').count(), 0);
    const banner = await page.locator('#ready-banner').boundingBox();
    const lawn = await page.locator('#lawn-grid').boundingBox();
    assert.ok(banner.y + banner.height <= lawn.y);
    await page.screenshot({path:'test-results/free-preparation.png',fullPage:true});
    await page.click('#start');
    assert.equal(await page.evaluate(() => __pvz.game.status), 'playing');
    assert.equal(await page.locator('.plant-entity').count(), 45);
    assert.equal(await page.locator('[data-type="Peashooter"] .seed-cost').textContent(), '100');
    await page.evaluate(() => __pvz.reset(1, 'adventure'));
    console.log('PASS preparation: all 45 cells clickable, free repeated planting, no timers/enemies before explicit start, preserved formation');

    assert.equal(await page.locator('#auto-collect').getAttribute('aria-pressed'), 'true');
    await page.evaluate(() => { __pvz.game.addSun(300, 200, true); __pvz.game.addSun(400, 300); });
    await page.waitForFunction(() => __pvz.game.sun === 200);
    assert.equal(await page.locator('.sun-entity').count(), 0);
    await page.click('#auto-collect');
    await page.evaluate(() => { __pvz.game.addSun(300, 200); });
    await page.waitForTimeout(1200);
    assert.equal(await page.evaluate(() => __pvz.game.sun), 200);
    await page.locator('.sun-entity').click();
    assert.equal(await page.locator('#sun-count').textContent(), '225');
    await page.reload();
    await page.locator('.seed-card').first().waitFor();
    assert.equal(await page.locator('#auto-collect').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.evaluate(() => __pvz.game.autoCollectSun), false);
    console.log('PASS auto pickup: default on, sky and plant sun collected, manual toggle, no duplicate collection, saved preference');
    await page.screenshot({ path: 'test-results/desktop-ready.png', fullPage: true });
    await page.locator('[data-row="0"][data-col="0"]').click();
    assert.equal(await page.locator('.plant-entity').count(), 0);
    assert.match(await page.locator('#toast').textContent(), /先开始冒险/);
    assert.equal(await page.locator('[data-type="Peashooter"] .seed-cost').textContent(), '100');
    await page.click('#start');
    await page.locator('[data-row="0"][data-col="0"]').click();
    assert.equal(await page.locator('#sun-count').textContent(), '100');
    await page.keyboard.press('2');
    await page.locator('[data-row="0"][data-col="1"]').click();
    assert.equal(await page.locator('#sun-count').textContent(), '0');
    assert.equal(await page.locator('.plant-entity').count(), 2);
    await page.locator('[data-row="0"][data-col="1"]').click();
    assert.match(await page.locator('#toast').textContent(), /已经有植物/);
    await page.waitForTimeout(3300);
    await page.locator('.sun-entity').first().click();
    assert.ok(Number(await page.locator('#sun-count').textContent()) >= 25);
    await page.keyboard.press('Space');
    assert.equal(await page.evaluate(() => __pvz.game.status), 'paused');
    const pausedTime = await page.evaluate(() => __pvz.game.time);
    await page.waitForTimeout(350);
    assert.equal(await page.evaluate(() => __pvz.game.time), pausedTime);
    await page.keyboard.press('Space');
    assert.equal(await page.evaluate(() => __pvz.game.status), 'playing');
    await page.click('#almanac');
    assert.equal(await page.locator('.almanac-entry').count(), 8);
    assert.equal(await page.evaluate(() => __pvz.game.status), 'paused');
    await page.keyboard.press('Escape');
    assert.equal(await page.evaluate(() => __pvz.game.status), 'playing');
    await page.click('#help'); assert.ok(await page.locator('.instructions').isVisible()); await page.click('#close-dialog');
    await page.click('#sound'); assert.equal(await page.locator('#sound').getAttribute('aria-pressed'), 'true');
    await page.keyboard.press('s'); await page.locator('[data-row="0"][data-col="1"]').click();
    assert.equal(await page.locator('.plant-entity').count(), 1);
    await page.evaluate(() => {
      const g = __pvz.game; g.sun = 2000;
      for(let r=0;r<5;r++) {
        if(r>0){g.cooldowns.SunFlower=0;g.plant('SunFlower',r,0);}
        g.cooldowns.Peashooter=0;g.plant('Peashooter',r,2);
        g.cooldowns.WallNut=0;g.plant('WallNut',r,5);
      }
      __pvz.advance(Math.max(0.1, 66 - g.time));
    });
    assert.ok(await page.locator('.zombie-entity').count() > 0); assert.ok(await page.locator('.plant-entity').count() > 10);
    await page.screenshot({ path: 'test-results/desktop-battle.png', fullPage: true });
    await page.click('#restart'); await page.click('#cancel-restart'); assert.equal(await page.evaluate(() => __pvz.game.status), 'playing');
    await page.evaluate(() => { const g = __pvz.game; g.spawned = g.schedule.length; g.zombies.forEach(z => z.hp=0); g.step(.05); __pvz.render(); });
    assert.match(await page.locator('#dialog-content h2').textContent(), /小院安全/);
    await page.click('#next-game'); assert.equal(await page.evaluate(() => __pvz.game.autoCollectSun), false); assert.equal(await page.evaluate(() => __pvz.game.level), 2); assert.equal(await page.evaluate(() => __pvz.game.status), 'ready');
    await page.click('#start');
    await page.evaluate(() => { const g=__pvz.game;g.mowers[0].status='spent';g.spawn('Zombie',0,40);g.step(.05);__pvz.render(); });
    assert.match(await page.locator('#dialog-content h2').textContent(), /闯进/);
    await page.click('#next-game'); assert.equal(await page.evaluate(() => __pvz.game.status), 'ready');
    await page.click('#adventure'); assert.equal(await page.locator('[data-level="3"]').isDisabled(), true); await page.click('#close-dialog');
    console.log('PASS desktop: planting, costs, occupied cells, collection, pause, shortcuts, almanac, help, audio, shovel, combat, restart cancel, win, next level, loss, retry, unlocks');
    await page.evaluate(() => { __pvz.reset(1, 'free'); __pvz.game.sun = 2500; __pvz.render(); });
    await page.keyboard.press('7');
    await page.locator('[data-row="0"][data-col="0"]').click();
    assert.equal(await page.locator('#sun-count').textContent(), '2500');
    assert.equal(await page.locator('.divine-water-plant img').getAttribute('src'), 'assets/DivineWaterShooter.png');
    await page.locator('[data-row="4"][data-col="0"]').click();
    assert.equal(await page.locator('.divine-water-plant').count(), 2);
    assert.equal(await page.locator('#sun-count').textContent(), '2500');
    await page.click('#start');
    await page.evaluate(() => { const g=__pvz.game;g.spawn('Zombie',0,420);g.spawn('ConeheadZombie',0,560);g.spawn('BucketheadZombie',0,740);g.spawn('Zombie',1,600);__pvz.advance(0.6); });
    assert.ok(await page.locator('.pea.water').count() > 0);
    await page.evaluate(() => __pvz.advance(1.2));
    assert.equal(await page.evaluate(() => __pvz.game.kills), 3);
    assert.equal(await page.evaluate(() => __pvz.game.zombies[0].hp), 180);
    await page.screenshot({ path: 'test-results/divine-water-desktop.png', fullPage: true });
    await page.click('#almanac');
    assert.ok(await page.locator('.almanac-entry').filter({hasText:'神水滴射手'}).isVisible());
    await page.click('#close-dialog');
    console.log('PASS divine water shooter: shortcut 7, plant sprite, free repeated planting, piercing combat, almanac');

    const progressBeforeBoss = await page.evaluate(() => localStorage.getItem('pvz-best-level'));
    await page.click('#boss-challenge');
    assert.equal(await page.evaluate(() => __pvz.game.bossChallenge), true);
    assert.equal(await page.evaluate(() => __pvz.game.status), 'ready');
    assert.equal(await page.locator('#boss-health').isVisible(), false);
    await page.keyboard.press('3');
    await page.locator('[data-row="2"][data-col="4"]').click();
    await page.click('#start');
    await page.locator('.boss-entity').waitFor();
    assert.match(await page.locator('#boss-health-value').textContent(), /12000/);
    await page.evaluate(() => __pvz.advance(Math.max(0.1,13.25 - __pvz.game.time)));
    assert.ok(await page.locator('.zombie-entity').count() >= 2);
    assert.equal(await page.locator('.boss-target').count(), 1);
    await page.mouse.move(50, 50);
    await page.screenshot({path:'test-results/boss-battle.png',fullPage:true});
    await page.keyboard.press('Space');
    const markBeforePause = await page.evaluate(() => __pvz.game.zombies.find(z=>z.isBoss).mark.remaining);
    await page.waitForTimeout(250);
    assert.equal(await page.evaluate(() => __pvz.game.zombies.find(z=>z.isBoss).mark.remaining),markBeforePause);
    await page.keyboard.press('Space');
    await page.evaluate(() => __pvz.advance(2.1));
    assert.equal(await page.evaluate(() => __pvz.game.plants[0].hp),600);
    await page.evaluate(() => { __pvz.game.zombies.find(z=>z.isBoss).hp=6000;__pvz.advance(.1); });
    assert.match(await page.locator('#boss-health-title').textContent(), /暴走/);
    await page.evaluate(() => { __pvz.game.sun=1000;__pvz.render(); });
    await page.keyboard.press('7');
    await page.locator('[data-row="2"][data-col="0"]').click();
    await page.evaluate(() => __pvz.advance(2));
    assert.equal(await page.evaluate(() => __pvz.game.bossDefeated),true);
    assert.equal(await page.evaluate(() => __pvz.game.status),'playing');
    await page.evaluate(() => { __pvz.game.zombies.forEach(z=>{z.hp=0});__pvz.advance(.1); });
    assert.match(await page.locator('#dialog-content h2').textContent(), /僵王已击败/);
    assert.equal(await page.evaluate(() => localStorage.getItem('pvz-best-level')),progressBeforeBoss);
    await page.click('#next-game');
    assert.equal(await page.evaluate(() => __pvz.game.bossChallenge),true);
    assert.equal(await page.evaluate(() => __pvz.game.status),'ready');
    await page.click('#adventure');await page.locator('[data-level="1"]').click();
    assert.equal(await page.evaluate(() => __pvz.game.bossChallenge),false);
    console.log('PASS boss: direct challenge, manual preparation, arrival, health, summons, smash warning, pause, impact, enrage, divine damage, cleanup victory, retry, independent progress');

    await page.click('#mode-free');
    assert.equal(await page.evaluate(() => __pvz.game.mode),'free');
    assert.equal(await page.locator('#mode-free').getAttribute('aria-pressed'),'true');
    assert.match(await page.locator('#ready-description').textContent(), /先免费种植/);
    await page.keyboard.press('7');
    for (let row=0; row<5; row++) await page.locator(`[data-row="${row}"][data-col="0"]`).click();
    assert.equal(await page.locator('.divine-water-plant').count(),5);
    assert.equal(await page.locator('#sun-count').textContent(),'150');
    await page.evaluate(() => __pvz.advance(300));
    assert.equal(await page.evaluate(() => __pvz.game.time),0);
    await page.click('#mode-free');
    assert.equal(await page.locator('.divine-water-plant').count(),5);
    await page.screenshot({path:'test-results/free-mode.png',fullPage:true});
    await page.click('#start');
    assert.equal(await page.locator('[data-type="DivineWaterShooter"] .seed-cost').textContent(),'1000');
    await page.locator('[data-row="0"][data-col="1"]').click();
    assert.match(await page.locator('#toast').textContent(), /阳光不足/);
    await page.evaluate(() => __pvz.advance(18.1));
    assert.ok(await page.evaluate(() => __pvz.game.spawned > 0));
    await page.evaluate(() => __pvz.advance(200));
    assert.equal(await page.evaluate(() => __pvz.game.status),'won');
    assert.match(await page.locator('#dialog-content h2').textContent(), /自由模式守护成功/);
    assert.equal(await page.evaluate(() => localStorage.getItem('pvz-best-level')),progressBeforeBoss);
    await page.locator('#dialog [data-mode="boss"]').click();
    assert.equal(await page.evaluate(() => __pvz.game.mode),'boss');
    assert.equal(await page.evaluate(() => __pvz.game.status),'ready');
    assert.equal(await page.locator('#dialog').isVisible(),false);
    assert.equal(await page.locator('.plant-entity').count(),0);
    await page.click('#start');await page.evaluate(()=>__pvz.advance(3.2));
    await page.keyboard.press('Space');
    await page.locator('#dialog [data-mode="adventure"]').click();
    assert.equal(await page.locator('.boss-entity').count(),0);
    assert.equal(await page.locator('#boss-health').isVisible(),false);
    assert.equal(await page.evaluate(() => __pvz.game.status),'ready');
    for (const from of ['adventure','free','boss']) for (const to of ['adventure','free','boss']) {
      if (from === to) continue;
      await page.locator(`.mode-bar [data-mode="${from}"]`).click();
      await page.locator(`.mode-bar [data-mode="${to}"]`).click();
      assert.equal(await page.evaluate(() => __pvz.game.mode),to);
      assert.equal(await page.locator(`.mode-bar [data-mode="${to}"]`).getAttribute('aria-pressed'),'true');
      assert.equal(await page.evaluate(() => __pvz.game.time),0);
    }
    await page.click('#mode-free');await page.click('#start');
    await page.evaluate(()=>{__pvz.game.spawn('Zombie',0,40);__pvz.game.mowers[0].status='spent';__pvz.advance(.1);});
    assert.equal(await page.evaluate(() => __pvz.game.status),'lost');
    await page.locator('#dialog [data-mode="adventure"]').click();
    assert.equal(await page.evaluate(() => __pvz.game.mode),'adventure');
    assert.equal(await page.evaluate(() => localStorage.getItem('pvz-best-level')),progressBeforeBoss);
    console.log('PASS modes: all six transitions, adventure economy, free preparation then waves/victory, pause/result switching, entity cleanup, independent campaign progress');

    await page.evaluate(() => __pvz.reset(1, 'free'));
    await page.keyboard.press('8');
    await page.locator('[data-row="2"][data-col="0"]').click();
    await page.locator('[data-row="3"][data-col="0"]').click();
    assert.equal(await page.locator('.melon-plant').count(), 2);
    assert.equal(await page.locator('.melon-plant img').first().getAttribute('src'), 'assets/MelonPult.png');
    await page.click('#start');
    await page.evaluate(() => { const g = __pvz.game; g.spawn('BucketheadZombie', 2, 540); g.spawn('BucketheadZombie', 1, 550); __pvz.advance(.45); g.pause(); });
    assert.equal(await page.locator('.melon-projectile').count(), 1);
    await page.waitForTimeout(300); // Let the planting animation settle while the simulation is paused.
    await page.screenshot({ path: 'test-results/melon-desktop.png', fullPage: true });
    await page.evaluate(() => { __pvz.game.resume(); __pvz.advance(1); });
    assert.deepEqual(await page.evaluate(() => __pvz.game.zombies.map(z => z.hp)), [920, 974]);
    assert.ok(await page.locator('.melon-splash').count() > 0);
    await page.click('#almanac');
    assert.ok(await page.locator('.almanac-entry').filter({ hasText: '西瓜投手' }).isVisible());
    await page.click('#close-dialog');
    console.log('PASS melon: shortcut 8, repeated preparation, sprite, airborne projectile, direct/splash impact, almanac');

    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
    mobile.on('pageerror', e => errors.push(e.message));
    await mobile.goto(`${base}?test=1`);
    await mobile.locator('#start').tap();
    await mobile.locator('[data-row="0"][data-col="0"]').tap();
    assert.equal(await mobile.locator('#sun-count').textContent(), '100');
    assert.equal(await mobile.evaluate(() => __pvz.game.status), 'playing');
    const noOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
    assert.ok(noOverflow, 'mobile should not scroll horizontally');

    await mobile.evaluate(() => { __pvz.reset(1, 'free'); __pvz.game.sun=1000; __pvz.render(); });
    const waterCard = mobile.locator('[data-type="DivineWaterShooter"]');
    await waterCard.scrollIntoViewIfNeeded();
    await waterCard.tap();
    await mobile.locator('[data-row="0"][data-col="0"]').tap();
    assert.equal(await mobile.locator('.divine-water-plant').count(), 1);
    assert.ok(await mobile.locator('#start').isVisible());
    await mobile.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    await mobile.locator('#boss-challenge').tap();await mobile.locator('#start').tap();
    await mobile.evaluate(()=>__pvz.advance(3.2));
    assert.equal(await mobile.locator('.boss-entity').count(),1);
    assert.equal(await mobile.locator('#boss-health').isVisible(),true);
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await mobile.screenshot({path:'test-results/mobile-boss.png',fullPage:true});
    await mobile.locator('#mode-free').tap();
    assert.equal(await mobile.evaluate(()=>__pvz.game.mode),'free');
    await mobile.locator('#start').tap();await mobile.evaluate(()=>__pvz.advance(18.1));
    assert.equal(await mobile.locator('.zombie-entity').count(),1);
    await mobile.screenshot({path:'test-results/mobile-modes.png',fullPage:true});
    await mobile.locator('#mode-adventure').tap();
    assert.equal(await mobile.evaluate(()=>__pvz.game.mode),'adventure');
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await mobile.close(); console.log('PASS mobile: touch planting, start and no horizontal overflow');
    for (const entry of ['index.html', 'dist/index.html']) {
      await page.goto(pathToFileURL(path.resolve(entry)).href);
      await page.locator('.seed-card').first().waitFor();
      await page.click('#start');
      await page.locator('[data-row="0"][data-col="0"]').click();
      assert.equal(await page.locator('#sun-count').textContent(), '100');
      assert.equal(await page.locator('#scene-status').textContent(), '守护进行中');
      const broken = await page.locator('img').evaluateAll(images => images.filter(i => !i.complete || !i.naturalWidth).map(i => i.src));
      assert.deepEqual(broken, [], `${entry} has missing images`);
      assert.equal(await page.locator('.lawn-grid').evaluate(el => getComputedStyle(el).display), 'grid');
      assert.match(await page.locator('.scene').evaluate(el => getComputedStyle(el).backgroundImage), /lawn/);
      await page.locator('.brand').click();
      await page.locator('.seed-card').first().waitFor();
      assert.equal(await page.locator('#sun-count').textContent(), '150');
      console.log(`PASS direct file: ${entry}`);
    }
    assert.deepEqual(errors, []); console.log('PASS zero browser errors / HTTP errors');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
